In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\AX\Desktop\gadm1_nuts2-gadm1_nuts2-fb-social-connectedness-index-october-2021.tsv', sep='\t')

In [4]:
df.head(50)

   user_loc fr_loc  scaled_sci
0       ABW    ABW    28858054
1       ABW   AGO1          96
2       ABW  AGO10          86
3       ABW  AGO11          81
4       ABW  AGO12          56
5       ABW  AGO13          94
6       ABW  AGO14          76
7       ABW  AGO15          65
8       ABW  AGO16         111
9       ABW  AGO17          73
10      ABW  AGO18          82
11      ABW   AGO2          93
12      ABW   AGO3         107
13      ABW   AGO4          73
14      ABW   AGO5         102
15      ABW   AGO6          84
16      ABW   AGO7          92
17      ABW   AGO8         112
18      ABW   AGO9          85
19      ABW   AL01          38
20      ABW   AL02          97
21      ABW   AL03          33
22      ABW    AND         609
23      ABW   ARE1         212
24      ABW   ARE2          86
25      ABW   ARE3         341
26      ABW   ARE4         104
27      ABW   ARE5          15
28      ABW   ARE6         103
29      ABW   ARE7         107
30      ABW   ARE8          82
31      ABW   ARG1         380
32      ABW  ARG10         147
33      ABW  ARG11         190
34      ABW  ARG12         156
35      ABW  ARG13         448
36      ABW  ARG14         170
37      ABW  ARG15         492
38      ABW  ARG16         407
39      ABW  ARG17         195
40      ABW  ARG18         171
41      ABW  ARG19         213
42      ABW   ARG2         277
43      ABW  ARG20         287
44      ABW  ARG21         233
45      ABW  ARG22         153
46      ABW  ARG23         368
47      ABW  ARG24         214
48      ABW   ARG3         135
49      ABW   ARG4         176